version: '3'

services:
  todo-app:
    build: .
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    depends_on:
      - db
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo-db
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres: